# -*- coding: utf-8 -*-
"""WIDS25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RcsO7HgITYPr8gBTYRlPTLRCBvYpV_7S
"""

import pandas as pd

df=pd.read_csv('second_order_df.csv')

from numpy import info
print(df.info())

df["isError"].value_counts()

df["TimeStamp"]=pd.to_datetime(df["TimeStamp"], unit="s")

df["label"] = df["isError"]

addr_features = df.groupby("From").agg(
    tx_count=("TxHash", "count"),
    avg_value=("Value", "mean"),
    total_value=("Value", "sum"),
    error_rate=("label", "mean"),
    unique_receivers=("To", "nunique")
).reset_index()

time_features = df.groupby("From")["TimeStamp"].agg(
    first_tx="min",
    last_tx="max"
).reset_index()

time_features["active_days"] = (
    time_features["last_tx"] - time_features["first_tx"]
).dt.total_seconds() / 86400

features = addr_features.merge(time_features, on="From")

features["wallet_label"] = (features["error_rate"] > 0).astype(int)

print(features["wallet_label"].value_counts())

X = features.drop(columns=[
    "From",
    "first_tx",
    "last_tx",
    "error_rate",
    "wallet_label"
])

y = features["wallet_label"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

fraud = y_train.sum()
legit = len(y_train) - fraud
scale_pos_weight = legit / fraud

from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

import joblib

joblib.dump(model, "xgb_fraud_model.pkl")
print("Model saved successfully")